import type { Category, CategoryMeta, NewsItem, Product } from "@/types";

const img = (file: string) => `/images/${file}`;

export const HERO_IMAGE = img("hero.jpg");
export const HERO_SECONDARY_IMAGE = img("vapor-glide.jpg");
export const courtSurgeImage = img("court-surge-01.jpg");

export const CATEGORY_META: Record<Category, CategoryMeta> = {
  shoes: {
    slug: "shoes",
    label: "Shoes",
    short: "Kicks",
    color: "#2B5CFF",
    tagline: "Heat for every court, street and trail.",
  },
  jerseys: {
    slug: "jerseys",
    label: "Jerseys",
    short: "Kits",
    color: "#0FA36B",
    tagline: "Team up. Kits made for the block.",
  },
  shorts: {
    slug: "shorts",
    label: "Shorts",
    short: "Tracks",
    color: "#FF6B2C",
    tagline: "Run, jump, post up — light and free.",
  },
  shirts: {
    slug: "shirts",
    label: "Shirts",
    short: "Tees",
    color: "#8B3FF0",
    tagline: "Tees that carry the whole drop.",
  },
  other: {
    slug: "other",
    label: "Other",
    short: "Extras",
    color: "#E0301E",
    tagline: "Caps, socks and match-ready extras.",
  },
};

export const CATEGORY_ORDER = Object.keys(CATEGORY_META) as Category[];

const usSizes = [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12];
const letterSizes = ["S", "M", "L", "XL", "XXL"];

export function defaultSizeLabel(p: Product): string {
  if (p.sizeType === "none") return "One Size";
  if (p.sizeType === "letter") return "L";
  return `US ${p.sizes[Math.floor(p.sizes.length / 2)]}`;
}

export function sizeLabel(p: Product, s: number | string): string {
  if (p.sizeType === "us") return `US ${s}`;
  return String(s);
}

export const PRODUCTS: Product[] = [
  // SHOES
  {
    id: "vapor-glide",
    name: "Vapor Glide",
    brand: "SICKS Athletics",
    price: 149,
    category: "shoes",
    image: img("vapor-glide.jpg"),
    rating: 4.8,
    isNew: true,
    featured: true,
    colors: ["#FF3B30", "#111114", "#F2F2F2"],
    sizes: usSizes,
    sizeType: "us",
    tagline: "Carbon-plated race-day speed.",
  },
  {
    id: "velocity-knit",
    name: "Velocity Knit",
    brand: "SICKS Lab",
    price: 129,
    category: "shoes",
    image: img("velocity-knit.jpg"),
    rating: 4.6,
    isNew: false,
    featured: true,
    colors: ["#E8E8EC", "#D84B35", "#23262F"],
    sizes: usSizes,
    sizeType: "us",
    tagline: "Everyday knit trainer that disappears on foot.",
  },
  {
    id: "trail-rift-gtx",
    name: "Trail Rift GTX",
    brand: "SICKS",
    price: 165,
    category: "shoes",
    image: img("trail-rift-gtx.jpg"),
    rating: 4.7,
    isNew: true,
    featured: false,
    colors: ["#3E4E37", "#7C8B6F", "#111114"],
    sizes: usSizes,
    sizeType: "us",
    tagline: "Waterproof grip for wet days out back.",
  },
  {
    id: "court-surge-01",
    name: "Court Surge 01",
    brand: "SICKS",
    price: 185,
    category: "shoes",
    image: img("court-surge-01.jpg"),
    rating: 4.9,
    isNew: true,
    featured: true,
    colors: ["#1D5FEE", "#FF6B2C", "#111114"],
    sizes: usSizes,
    sizeType: "us",
    tagline: "Low-cut lockdown for quick first steps.",
  },
  {
    id: "fastbreak-x",
    name: "Fastbreak X",
    brand: "SICKS Athletics",
    price: 199,
    category: "shoes",
    image: img("fastbreak-x.jpg"),
    rating: 4.8,
    isNew: true,
    featured: false,
    colors: ["#111114", "#E8E8EC", "#FF2D78"],
    sizes: usSizes,
    sizeType: "us",
    tagline: "Bouncy foam, deeper cuts, harder stops.",
  },
  {
    id: "street-comet",
    name: "Street Comet",
    brand: "SICKS",
    price: 119,
    category: "shoes",
    image: img("street-comet.jpg"),
    rating: 4.5,
    isNew: false,
    featured: false,
    colors: ["#111114", "#7A7A7A", "#FF6B2C"],
    sizes: usSizes,
    sizeType: "us",
    tagline: "The all-day sneaker, no cap.",
  },
  {
    id: "hardwood-king",
    name: "Hardwood King",
    brand: "SICKS",
    price: 189,
    category: "shoes",
    image: img("hardwood-king.jpg"),
    rating: 4.6,
    isNew: false,
    featured: false,
    colors: ["#E4A853", "#111114", "#F2F2F2"],
    sizes: usSizes,
    sizeType: "us",
    tagline: "Court shoe built for back-to-back runs.",
  },
  {
    id: "core-pump",
    name: "Core Pump",
    brand: "SICKS Lab",
    price: 125,
    category: "shoes",
    image: img("core-pump.jpg"),
    rating: 4.6,
    isNew: false,
    featured: false,
    colors: ["#111114", "#2B5CFF", "#F2F2F2"],
    sizes: usSizes,
    sizeType: "us",
    tagline: "Gym floor favorite for lifts and lunges.",
  },

  // JERSEYS
  {
    id: "vince-carter-jersey",
    name: "Vince Carter - Raptors",
    brand: "SICKS basketball Club",
    price: 89,
    category: "jerseys",
    image: img("jersey-carter.webp"),
    rating: 4.9,
    isNew: false,
    featured: false,
    colors: ["#3e026b", "#F2F2F2"],
    sizes: letterSizes,
    sizeType: "letter",
    tagline: "Raptors legend. The Air Canada. ",
  },
  {
    id: "lebron-james-jersey",
    name: "Lebron James - Lakers ",
    brand: "SICKS Basketball Club",
    price: 89,
    category: "jerseys",
    image: img("jersey-lebron.webp"),
    rating: 4.9,
    isNew: true,
    featured: true,
    colors: ["#f5e342", "#aa42f5"],
    sizes: letterSizes,
    sizeType: "letter",
    tagline: "Lakers legend. King of the court.",
  },
  {
    id: "stephen-curry-jersey",
    name: "Stephen Curry - Warriors",
    brand: "SICKS Basketball Club",
    price: 89,
    category: "jerseys",
    image: img("jersey-curry.webp"),
    rating: 4.8,
    isNew: true,
    featured: false,
    colors: ["#F2F2F2", "#1a0cb3"],
    sizes: letterSizes,
    sizeType: "letter",
    tagline: "Warrior finest. Shoot from anywhere.",
  },
  {
    id: "michael-jordan-jersey",
    name: "Michael Jordan - Bulls",
    brand: "SICKS basketball Club",
    price: 89,
    category: "jerseys",
    image: img("jersey-jordan.webp"),
    rating: 4.8,
    isNew: false,
    featured: true,
    colors: ["#d10a0a", "#F2F2F2"],
    sizes: letterSizes,
    sizeType: "letter",
    tagline: "Bulls legend. Airness on the court.",
  },
  {
    id: "wembanyama-jersey",
    name: "Victor Wembanyama - Spurs",
    brand: "SICKS basketball Club",
    price: 89,
    category: "jerseys",
    image: img("jersey-wemby.webp"),
    rating: 4.7,
    isNew: true,
    featured: false,
    colors: ["#111114", "#F2F2F2"],
    sizes: letterSizes,
    sizeType: "letter",
    tagline: "Spurs rising star and The future.",
  },
  {
    id: "jalen-brunson-jersey",
    name: "Jalen Brunson - Knicks",
    brand: "SICKS Basketball Club",
    price: 89,
    category: "jerseys",
    image: img("jersey-brunson.webp"),
    rating: 4.5,
    isNew: false,
    featured: false,
    colors: ["#0a10c9", "#F2F2F2"],
    sizes: letterSizes,
    sizeType: "letter",
    tagline: "Knicks star. Playmaker on the court.",
  },
  {
    id: "anthony-edwards-jersey",
    name: "Anthony Edwards - Timberwolves",
    brand: "SICKS Basketball Club",
    price: 89,
    category: "jerseys",
    image: img("jersey-edwards.webp"),
    rating: 4.6,
    isNew: false,
    featured: false,
    colors: ["#F2F2F2", "#111114"],
    sizes: letterSizes,
    sizeType: "letter",
    tagline: "Timberwolves high-flyer.",
  },
  {
    id: "jaylen-brown-jersey",
    name: "Jaylen Brown - Celtics",
    brand: "SICKS Basketball Club",
    price: 89,
    category: "jerseys",
    image: img("jersey-brown.webp"),
    rating: 4.6,
    isNew: false,
    featured: false,
    colors: ["#111114", "#F2F2F2"],
    sizes: letterSizes,
    sizeType: "letter",
    tagline: "Celtics scoring machine.",
  },
  {
    id: "lamine-jersey",
    name: "Lamine Yamal - Spain",
    brand: "SICKS Football Club",
    price: 89,
    category: "jerseys",
    image: img("jersey-yamal.webp"),
    rating: 4.8,
    isNew: false,
    featured: false,
    colors: ["#990202", "#F2F2F2"],
    sizes: letterSizes,
    sizeType: "letter",
    tagline: "Spain's youngest Superstar. ",
  },
  {
    id: "lionel-messi-jersey",
    name: "Lionel Messi - Argentina",
    brand: "SICKS Football Club",
    price: 89,
    category: "jerseys",
    image: img("jersey-messi.webp"),
    rating: 5.0,
    isNew: false,
    featured: false,
    colors: ["#02b6ed", "#060252"],
    sizes: letterSizes,
    sizeType: "letter",
    tagline: "The greatest of all time.",
  },
  {
    id: "harry-kane-jersey",
    name: "Harry Kane - FC Bayern ",
    brand: "SICKS Football Club",
    price: 89,
    category: "jerseys",
    image: img("jersey-kane.webp"),
    rating: 4.7,
    isNew: false,
    featured: false,
    colors: ["#c71202", "#F2F2F2"],
    sizes: letterSizes,
    sizeType: "letter",
    tagline: "FC Bayern's captain. Goal machine.",
  },
  {
    id: "kylian-mbappe-jersey",
    name: "Kylian Mbappé - Real Madrid",
    brand: "SICKS Football Club",
    price: 89,
    category: "jerseys",
    image: img("jersey-mbappe.webp"),
    rating: 4.9,
    isNew: false,
    featured: false,
    colors: ["#F2F2F2", "#0a0075"],
    sizes: letterSizes,
    sizeType: "letter",
    tagline: "Real Madrid's Speedster.",
  },

  // SHIRTS
  {
    id: "box-logo-tee",
    name: "Box Logo Tee",
    brand: "SICKS",
    price: 34,
    category: "shirts",
    image: img("box-logo-tee.jpg"),
    rating: 4.6,
    isNew: false,
    featured: true,
    colors: ["#F2F2F2", "#111114", "#2B5CFF"],
    sizes: letterSizes,
    sizeType: "letter",
    tagline: "The box logo. The original flex.",
  },
  {
    id: "heavyweight-tee",
    name: "Heavyweight Tee",
    brand: "SICKS Lab",
    price: 38,
    category: "shirts",
    image: img("heavyweight-tee.jpg"),
    rating: 4.7,
    isNew: true,
    featured: false,
    colors: ["#111114", "#F2F2F2", "#8B3FF0"],
    sizes: letterSizes,
    sizeType: "letter",
    tagline: "240gsm cotton that holds its shape.",
  },
  {
    id: "graphic-drop-tee",
    name: "Graphic Drop Tee",
    brand: "SICKS",
    price: 36,
    category: "shirts",
    image: img("graphic-drop-tee.jpg"),
    rating: 4.8,
    isNew: true,
    featured: true,
    colors: ["#F2F2F2", "#111114", "#E0301E"],
    sizes: letterSizes,
    sizeType: "letter",
    tagline: "FW26 graphic, dropped once.",
  },
  {
    id: "player-tee",
    name: "Player Tee",
    brand: "SICKS Ball Club",
    price: 32,
    category: "shirts",
    image: img("player-tee.jpg"),
    rating: 4.5,
    isNew: false,
    featured: false,
    colors: ["#111114", "#F2F2F2", "#0FA36B"],
    sizes: letterSizes,
    sizeType: "letter",
    tagline: "Club-issue tee, everyday wear.",
  },
  {
    id: "performance-tee",
    name: "Performance Tee",
    brand: "SICKS Athletics",
    price: 40,
    category: "shirts",
    image: img("performance-tee.jpg"),
    rating: 4.4,
    isNew: false,
    featured: false,
    colors: ["#2B5CFF", "#111114", "#F2F2F2"],
    sizes: letterSizes,
    sizeType: "letter",
    tagline: "Dry-fit quick layer for training.",
  },
  {
    id: "collab-tee",
    name: "Collab Tee",
    brand: "SICKS × Blockstar",
    price: 44,
    category: "shirts",
    image: img("collab-tee.jpg"),
    rating: 4.9,
    isNew: true,
    featured: true,
    colors: ["#111114", "#FF6B2C", "#F2F2F2"],
    sizes: letterSizes,
    sizeType: "letter",
    tagline: "Limited collab. Gone when it's gone.",
  },
  {
    id: "longsleeve-base",
    name: "Longsleeve Base",
    brand: "SICKS",
    price: 42,
    category: "shirts",
    image: img("longsleeve-base.jpg"),
    rating: 4.5,
    isNew: false,
    featured: false,
    colors: ["#111114", "#F2F2F2", "#2B5CFF"],
    sizes: letterSizes,
    sizeType: "letter",
    tagline: "Cold-start base layer under the kit.",
  },

  // SHORTS
  {
    id: "court-shorts-pro",
    name: "Court Shorts Pro",
    brand: "SICKS Ball Club",
    price: 49,
    category: "shorts",
    image: img("court-shorts-pro.jpg"),
    rating: 4.7,
    isNew: false,
    featured: true,
    colors: ["#111114", "#F2F2F2", "#0FA36B"],
    sizes: letterSizes,
    sizeType: "letter",
    tagline: "Match-day short with a secure phone pocket.",
  },
  {
    id: "sweat-shorts-heavy",
    name: "Sweat Shorts Heavy",
    brand: "SICKS Lab",
    price: 45,
    category: "shorts",
    image: img("sweat-shorts-heavy.jpg"),
    rating: 4.6,
    isNew: false,
    featured: false,
    colors: ["#111114", "#7A7A7A", "#F2F2F2"],
    sizes: letterSizes,
    sizeType: "letter",
    tagline: "Fleece-backed, slouched fit.",
  },
  {
    id: "track-split-shorts",
    name: "Track Split Shorts",
    brand: "SICKS Athletics",
    price: 42,
    category: "shorts",
    image: img("track-split-shorts.jpg"),
    rating: 4.5,
    isNew: true,
    featured: false,
    colors: ["#FF6B2C", "#111114", "#F2F2F2"],
    sizes: letterSizes,
    sizeType: "letter",
    tagline: "Side splits for full stride.",
  },
  {
    id: "b-ball-shorts",
    name: "B-ball Shorts",
    brand: "SICKS",
    price: 48,
    category: "shorts",
    image: img("b-ball-shorts.jpg"),
    rating: 4.8,
    isNew: true,
    featured: true,
    colors: ["#F2F2F2", "#2B5CFF", "#111114"],
    sizes: letterSizes,
    sizeType: "letter",
    tagline: "Classic mid-length with inner liner.",
  },
  {
    id: "gym-shorts-flex",
    name: "Gym Shorts Flex",
    brand: "SICKS",
    price: 39,
    category: "shorts",
    image: img("gym-shorts-flex.jpg"),
    rating: 4.4,
    isNew: false,
    featured: false,
    colors: ["#111114", "#8B3FF0", "#F2F2F2"],
    sizes: letterSizes,
    sizeType: "letter",
    tagline: "Four-way stretch, zero chafe.",
  },
  {
    id: "team-shorts-87",
    name: "Team Shorts 87",
    brand: "SICKS",
    price: 44,
    category: "shorts",
    image: img("team-shorts-87.jpg"),
    rating: 4.6,
    isNew: false,
    featured: false,
    colors: ["#111114", "#E0301E", "#F2F2F2"],
    sizes: letterSizes,
    sizeType: "letter",
    tagline: "Retro-striped shorts from the vault.",
  },

  // OTHER
  {
    id: "trucker-cap",
    name: "Trucker Cap",
    brand: "SICKS",
    price: 28,
    category: "other",
    image: img("trucker-cap.jpg"),
    rating: 4.6,
    isNew: true,
    featured: true,
    colors: ["#E0301E", "#111114", "#F2F2F2"],
    sizes: [],
    sizeType: "none",
    tagline: "Curved brim, snapback, one size fits hype.",
  },
  {
    id: "crew-socks-3pack",
    name: "Crew Socks 3-Pack",
    brand: "SICKS Lab",
    price: 18,
    category: "other",
    image: img("crew-socks-3pack.jpg"),
    rating: 4.5,
    isNew: false,
    featured: false,
    colors: ["#111114", "#F2F2F2", "#2B5CFF"],
    sizes: [],
    sizeType: "none",
    tagline: "Cushioned crews in three colorways.",
  },
  {
    id: "match-ball-pro",
    name: "Match Ball Pro",
    brand: "SICKS",
    price: 55,
    category: "other",
    image: img("match-ball-pro.jpg"),
    rating: 4.8,
    isNew: true,
    featured: true,
    colors: ["#F2F2F2", "#111114"],
    sizes: [],
    sizeType: "none",
    tagline: "Tournament-ready match ball.",
  },
  {
    id: "street-ball",
    name: "Street Ball",
    brand: "SICKS",
    price: 45,
    category: "other",
    image: img("street-ball.jpg"),
    rating: 4.6,
    isNew: false,
    featured: false,
    colors: ["#FF6B2C", "#111114"],
    sizes: [],
    sizeType: "none",
    tagline: "Outdoor basketball built for the blacktop.",
  },
  {
    id: "training-bottle",
    name: "Training Bottle",
    brand: "SICKS Athletics",
    price: 22,
    category: "other",
    image: img("training-bottle.jpg"),
    rating: 4.3,
    isNew: false,
    featured: false,
    colors: ["#2B5CFF", "#111114", "#F2F2F2"],
    sizes: [],
    sizeType: "none",
    tagline: "Squeeze bottle, 750ml, gym proof.",
  },
  {
    id: "wristband-2pack",
    name: "Wristband 2-Pack",
    brand: "SICKS",
    price: 14,
    category: "other",
    image: img("wristband-2pack.jpg"),
    rating: 4.4,
    isNew: false,
    featured: false,
    colors: ["#111114", "#F2F2F2"],
    sizes: [],
    sizeType: "none",
    tagline: "Classic wristbands for the hard hours.",
  },
];

export const FEATURED = PRODUCTS.filter((p) => p.featured).slice(0, 4);

export function productsByCategory(category: Category): Product[] {
  return PRODUCTS.filter((p) => p.category === category);
}

export const NEWS: NewsItem[] = [
  {
    id: "collab-drop",
    title: "SICKS × Blockstar collab drops Friday 9AM",
    excerpt:
      "Limited run, one drop, no restock. Set your alarm before it's gone.",
    date: "Aug 12, 2026",
    tag: "Drop",
    tagColor: "#0FA36B",
    image: img("fastbreak-x.jpg"),
  },
  {
    id: "vapor-glide-lab-test",
    title: "Vapor Glide 2: the lab test",
    excerpt:
      "We put 100km on the new racer — here's the verdict from the SICKS lab.",
    date: "Aug 08, 2026",
    tag: "Review",
    tagColor: "#2B5CFF",
    image: img("trail-rift-gtx.jpg"),
  },
  {
    id: "court-surge-restock",
    title: "Court Surge 01 restock — sizes 9–11",
    excerpt:
      "Sold out in 48 hours, back on the shelf. Don't sleep on it this time.",
    date: "Aug 03, 2026",
    tag: "Restock",
    tagColor: "#FF6B2C",
    image: img("hardwood-king.jpg"),
  },
  {
    id: "fw26-colorways",
    title: "Inside the FW26 colorways",
    excerpt:
      "A first look at the palette dropping next week, straight from the studio.",
    date: "Jul 28, 2026",
    tag: "Inside",
    tagColor: "#8B3FF0",
    image: img("velocity-knit.jpg"),
  },
];
